# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Ids(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    number_0 = models.TextField(db_column='0', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.

    class Meta:
        managed = True
        db_table = 'ids'


class Pix(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    number_0 = models.FloatField(db_column='0', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_1 = models.FloatField(db_column='1', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_2 = models.FloatField(db_column='2', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_3 = models.FloatField(db_column='3', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_4 = models.FloatField(db_column='4', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_5 = models.FloatField(db_column='5', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_6 = models.FloatField(db_column='6', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_7 = models.FloatField(db_column='7', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_8 = models.FloatField(db_column='8', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_9 = models.FloatField(db_column='9', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_10 = models.FloatField(db_column='10', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_11 = models.FloatField(db_column='11', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_12 = models.FloatField(db_column='12', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_13 = models.FloatField(db_column='13', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_14 = models.FloatField(db_column='14', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_15 = models.FloatField(db_column='15', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_16 = models.FloatField(db_column='16', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_17 = models.FloatField(db_column='17', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_18 = models.FloatField(db_column='18', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_19 = models.FloatField(db_column='19', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_20 = models.FloatField(db_column='20', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_21 = models.FloatField(db_column='21', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_22 = models.FloatField(db_column='22', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_23 = models.FloatField(db_column='23', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_24 = models.FloatField(db_column='24', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_25 = models.FloatField(db_column='25', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_26 = models.FloatField(db_column='26', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_27 = models.FloatField(db_column='27', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_28 = models.FloatField(db_column='28', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_29 = models.FloatField(db_column='29', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_30 = models.FloatField(db_column='30', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_31 = models.FloatField(db_column='31', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_32 = models.FloatField(db_column='32', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_33 = models.FloatField(db_column='33', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_34 = models.FloatField(db_column='34', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_35 = models.FloatField(db_column='35', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_36 = models.FloatField(db_column='36', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_37 = models.FloatField(db_column='37', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_38 = models.FloatField(db_column='38', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_39 = models.FloatField(db_column='39', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_40 = models.FloatField(db_column='40', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_41 = models.FloatField(db_column='41', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_42 = models.FloatField(db_column='42', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_43 = models.FloatField(db_column='43', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_44 = models.FloatField(db_column='44', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_45 = models.FloatField(db_column='45', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_46 = models.FloatField(db_column='46', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_47 = models.FloatField(db_column='47', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_48 = models.FloatField(db_column='48', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_49 = models.FloatField(db_column='49', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_50 = models.FloatField(db_column='50', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_51 = models.FloatField(db_column='51', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_52 = models.FloatField(db_column='52', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_53 = models.FloatField(db_column='53', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_54 = models.FloatField(db_column='54', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_55 = models.FloatField(db_column='55', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_56 = models.FloatField(db_column='56', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_57 = models.FloatField(db_column='57', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_58 = models.FloatField(db_column='58', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_59 = models.FloatField(db_column='59', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_60 = models.FloatField(db_column='60', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_61 = models.FloatField(db_column='61', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_62 = models.FloatField(db_column='62', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_63 = models.FloatField(db_column='63', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_64 = models.FloatField(db_column='64', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_65 = models.FloatField(db_column='65', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_66 = models.FloatField(db_column='66', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_67 = models.FloatField(db_column='67', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_68 = models.FloatField(db_column='68', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_69 = models.FloatField(db_column='69', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_70 = models.FloatField(db_column='70', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_71 = models.FloatField(db_column='71', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_72 = models.FloatField(db_column='72', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_73 = models.FloatField(db_column='73', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_74 = models.FloatField(db_column='74', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_75 = models.FloatField(db_column='75', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_76 = models.FloatField(db_column='76', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_77 = models.FloatField(db_column='77', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_78 = models.FloatField(db_column='78', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_79 = models.FloatField(db_column='79', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_80 = models.FloatField(db_column='80', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_81 = models.FloatField(db_column='81', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_82 = models.FloatField(db_column='82', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_83 = models.FloatField(db_column='83', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_84 = models.FloatField(db_column='84', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_85 = models.FloatField(db_column='85', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_86 = models.FloatField(db_column='86', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_87 = models.FloatField(db_column='87', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_88 = models.FloatField(db_column='88', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_89 = models.FloatField(db_column='89', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_90 = models.FloatField(db_column='90', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_91 = models.FloatField(db_column='91', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_92 = models.FloatField(db_column='92', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_93 = models.FloatField(db_column='93', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_94 = models.FloatField(db_column='94', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_95 = models.FloatField(db_column='95', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_96 = models.FloatField(db_column='96', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_97 = models.FloatField(db_column='97', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_98 = models.FloatField(db_column='98', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_99 = models.FloatField(db_column='99', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_100 = models.FloatField(db_column='100', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_101 = models.FloatField(db_column='101', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_102 = models.FloatField(db_column='102', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_103 = models.FloatField(db_column='103', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_104 = models.FloatField(db_column='104', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_105 = models.FloatField(db_column='105', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_106 = models.FloatField(db_column='106', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_107 = models.FloatField(db_column='107', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_108 = models.FloatField(db_column='108', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_109 = models.FloatField(db_column='109', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_110 = models.FloatField(db_column='110', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_111 = models.FloatField(db_column='111', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_112 = models.FloatField(db_column='112', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_113 = models.FloatField(db_column='113', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_114 = models.FloatField(db_column='114', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_115 = models.FloatField(db_column='115', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_116 = models.FloatField(db_column='116', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_117 = models.FloatField(db_column='117', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_118 = models.FloatField(db_column='118', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_119 = models.FloatField(db_column='119', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_120 = models.FloatField(db_column='120', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_121 = models.FloatField(db_column='121', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_122 = models.FloatField(db_column='122', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_123 = models.FloatField(db_column='123', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_124 = models.FloatField(db_column='124', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_125 = models.FloatField(db_column='125', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_126 = models.FloatField(db_column='126', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_127 = models.FloatField(db_column='127', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_128 = models.FloatField(db_column='128', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_129 = models.FloatField(db_column='129', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_130 = models.FloatField(db_column='130', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_131 = models.FloatField(db_column='131', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_132 = models.FloatField(db_column='132', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_133 = models.FloatField(db_column='133', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_134 = models.FloatField(db_column='134', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_135 = models.FloatField(db_column='135', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_136 = models.FloatField(db_column='136', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_137 = models.FloatField(db_column='137', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_138 = models.FloatField(db_column='138', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_139 = models.FloatField(db_column='139', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_140 = models.FloatField(db_column='140', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_141 = models.FloatField(db_column='141', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_142 = models.FloatField(db_column='142', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_143 = models.FloatField(db_column='143', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_144 = models.FloatField(db_column='144', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_145 = models.FloatField(db_column='145', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_146 = models.FloatField(db_column='146', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_147 = models.FloatField(db_column='147', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_148 = models.FloatField(db_column='148', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_149 = models.FloatField(db_column='149', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_150 = models.FloatField(db_column='150', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_151 = models.FloatField(db_column='151', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_152 = models.FloatField(db_column='152', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_153 = models.FloatField(db_column='153', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_154 = models.FloatField(db_column='154', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_155 = models.FloatField(db_column='155', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_156 = models.FloatField(db_column='156', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_157 = models.FloatField(db_column='157', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_158 = models.FloatField(db_column='158', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_159 = models.FloatField(db_column='159', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_160 = models.FloatField(db_column='160', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_161 = models.FloatField(db_column='161', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_162 = models.FloatField(db_column='162', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_163 = models.FloatField(db_column='163', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_164 = models.FloatField(db_column='164', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_165 = models.FloatField(db_column='165', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_166 = models.FloatField(db_column='166', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_167 = models.FloatField(db_column='167', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_168 = models.FloatField(db_column='168', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_169 = models.FloatField(db_column='169', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_170 = models.FloatField(db_column='170', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_171 = models.FloatField(db_column='171', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_172 = models.FloatField(db_column='172', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_173 = models.FloatField(db_column='173', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_174 = models.FloatField(db_column='174', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_175 = models.FloatField(db_column='175', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_176 = models.FloatField(db_column='176', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_177 = models.FloatField(db_column='177', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_178 = models.FloatField(db_column='178', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_179 = models.FloatField(db_column='179', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_180 = models.FloatField(db_column='180', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_181 = models.FloatField(db_column='181', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_182 = models.FloatField(db_column='182', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_183 = models.FloatField(db_column='183', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_184 = models.FloatField(db_column='184', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_185 = models.FloatField(db_column='185', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_186 = models.FloatField(db_column='186', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_187 = models.FloatField(db_column='187', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_188 = models.FloatField(db_column='188', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_189 = models.FloatField(db_column='189', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_190 = models.FloatField(db_column='190', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_191 = models.FloatField(db_column='191', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_192 = models.FloatField(db_column='192', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_193 = models.FloatField(db_column='193', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_194 = models.FloatField(db_column='194', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_195 = models.FloatField(db_column='195', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_196 = models.FloatField(db_column='196', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_197 = models.FloatField(db_column='197', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_198 = models.FloatField(db_column='198', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_199 = models.FloatField(db_column='199', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_200 = models.FloatField(db_column='200', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_201 = models.FloatField(db_column='201', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_202 = models.FloatField(db_column='202', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_203 = models.FloatField(db_column='203', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_204 = models.FloatField(db_column='204', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_205 = models.FloatField(db_column='205', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_206 = models.FloatField(db_column='206', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_207 = models.FloatField(db_column='207', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_208 = models.FloatField(db_column='208', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_209 = models.FloatField(db_column='209', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_210 = models.FloatField(db_column='210', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_211 = models.FloatField(db_column='211', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_212 = models.FloatField(db_column='212', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_213 = models.FloatField(db_column='213', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_214 = models.FloatField(db_column='214', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_215 = models.FloatField(db_column='215', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_216 = models.FloatField(db_column='216', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_217 = models.FloatField(db_column='217', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_218 = models.FloatField(db_column='218', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_219 = models.FloatField(db_column='219', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_220 = models.FloatField(db_column='220', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_221 = models.FloatField(db_column='221', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_222 = models.FloatField(db_column='222', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_223 = models.FloatField(db_column='223', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_224 = models.FloatField(db_column='224', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_225 = models.FloatField(db_column='225', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_226 = models.FloatField(db_column='226', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_227 = models.FloatField(db_column='227', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_228 = models.FloatField(db_column='228', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_229 = models.FloatField(db_column='229', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_230 = models.FloatField(db_column='230', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_231 = models.FloatField(db_column='231', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_232 = models.FloatField(db_column='232', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_233 = models.FloatField(db_column='233', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_234 = models.FloatField(db_column='234', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_235 = models.FloatField(db_column='235', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_236 = models.FloatField(db_column='236', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_237 = models.FloatField(db_column='237', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_238 = models.FloatField(db_column='238', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_239 = models.FloatField(db_column='239', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_240 = models.FloatField(db_column='240', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_241 = models.FloatField(db_column='241', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_242 = models.FloatField(db_column='242', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_243 = models.FloatField(db_column='243', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_244 = models.FloatField(db_column='244', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_245 = models.FloatField(db_column='245', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_246 = models.FloatField(db_column='246', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_247 = models.FloatField(db_column='247', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_248 = models.FloatField(db_column='248', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_249 = models.FloatField(db_column='249', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_250 = models.FloatField(db_column='250', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_251 = models.FloatField(db_column='251', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_252 = models.FloatField(db_column='252', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_253 = models.FloatField(db_column='253', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_254 = models.FloatField(db_column='254', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_255 = models.FloatField(db_column='255', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    subject = models.TextField(blank=True, null=True)
    slice = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'pix'
